- type: replace
  path: /releases/-
  value:
    name: routing
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.159.0
    version: 0.159.0
    sha1: 739f663f976fea826595880cfd58470bc8d49172
- type: replace
  path: /instance_groups/name=nginx/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats: {from: nats, deployment: cf}
    properties:
      route_registrar:
        routes:
        - name: grafana
          port: 3000
          registration_interval: 60s
          uris:
          - "grafana.((system_domain))"
