# This file assumes influxdb_exporter is being used: ./monitor-influxdb.yml

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=concourse_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/concourse_alerts/*.alerts.yml

# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/name=concourse_dashboards?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_files/-
  value: /var/vcap/jobs/concourse_dashboards/*.json
