# This file assumes firehose_exporter is being used: ./monitor-cf.yml

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/-
  value:
    name: p_redis_alerts
    release: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/p_redis_alerts/*.alerts

# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/-
  value:
    name: p_redis_dashboards
    release: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_files/-
  value: /var/vcap/jobs/p_redis_dashboards/*.json
