# This file assumes bosh_exporter based Service Discovery is being used: ./monitor-bosh.yml

# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus/jobs/-
  value:
    name: consul_exporter
    release: prometheus
    properties:
      consul_exporter:
        consul_server: "((consul_server))"

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/-
  value:
    name: consul_alerts
    release: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/consul_alerts/*.alerts

# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/-
  value:
    name: consul_dashboards
    release: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_files/-
  value: /var/vcap/jobs/consul_dashboards/*.json
