name: prometheus

instance_groups:
  - name: alertmanager
    azs:
      - z1
    instances: 1
    vm_type: default
    persistent_disk_type: 1GB
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: alertmanager
        release: prometheus
        properties:
          alertmanager:
            mesh:
              password: ((alertmanager_mesh_password))
            route:
              receiver: default
            receivers:
              - name: default
            test_alert:
              daily: true

  - name: prometheus
    azs:
      - z1
    instances: 1
    vm_type: default
    persistent_disk_type: 10GB
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: prometheus
        release: prometheus
        properties:
          prometheus:
            rule_files:
              - /var/vcap/jobs/grafana_alerts/*.alerts
              - /var/vcap/jobs/prometheus_alerts/*.alerts
            scrape_configs:
              - job_name: prometheus
                static_configs:
                - targets:
                  - localhost:9090
      - name: prometheus_alerts
        release: prometheus

  - name: grafana
    azs:
      - z1
    instances: 1
    vm_type: default
    persistent_disk_type: 1GB
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: grafana
        release: prometheus
        properties:
          grafana:
            security:
              admin_user: admin
              admin_password: ((grafana_password))
              secret_key: ((grafana_secret_key))
            dashboards:
              json:
                enabled: true
            prometheus:
              dashboard_files:
                - /var/vcap/jobs/grafana_dashboards/*.json
                - /var/vcap/jobs/prometheus_dashboards/*.json
      - name: grafana_exporter
        release: prometheus
        properties:
          grafana_exporter:
            grafana:
              uri: http://localhost:3000
              username: admin
              password: ((grafana_password))
      - name: grafana_dashboards
        release: prometheus
      - name: prometheus_dashboards
        release: prometheus

  - name: nginx
    azs: [ z1 ]
    instances: 1
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: nginx
        release: prometheus
        properties:
          nginx:
            alertmanager:
              auth_username: admin
              auth_password: ((alertmanager_password))
            prometheus:
              auth_username: admin
              auth_password: ((prometheus_password))

variables:
  - name: alertmanager_password
    type: password
  - name: alertmanager_mesh_password
    type: password
  - name: prometheus_password
    type: password
  - name: grafana_password
    type: password
  - name: grafana_secret_key
    type: password

releases:
  - name: prometheus
    version: 18.1.0
    url: https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=18.1.0
    sha1: b4e4fbbb04701f55d4048a3923483f8c535bd343

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest
