---
name: prometheus
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18

releases:
 - name: prometheus
   version: latest

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

instance_groups:
  - name: alertmanager
    jobs:
      - name: alertmanager
    instances: 1
    vm_type: default
    stemcell: default
    persistent_disk_type: default
    azs:
      - default
    networks:
      - name: default

  - name: prometheus
    jobs:
      - name: blackbox_exporter
      - name: collectd_exporter
      - name: consul_exporter
      - name: firehose_exporter
      - name: github_exporter
      - name: graphite_exporter
      - name: haproxy_exporter
      #- name: mysqld_exporter
      - name: node_exporter
      - name: prometheus
      - name: prometheus_cloudfoundry
      - name: pushgateway
      - name: rabbitmq_exporter
      - name: redis_exporter
      - name: statsd_exporter
    instances: 1
    vm_type: default
    stemcell: default
    persistent_disk_type: default
    azs:
      - default
    networks:
      - name: default

  - name: grafana
    jobs:
      - name: grafana
    instances: 1
    vm_type: default
    stemcell: default
    persistent_disk_type: default
    azs:
      - default
    networks:
      - name: default

properties:
  alertmanager:
    route:
      receiver: default-receiver
    receivers:
      - name: default-receiver

  blackbox_exporter:
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s

  firehose_exporter:
    uaa:
      url: https://uaa.local.pcfdev.io
      client_id: prometheus-firehose
      client_secret: prometheus-client-secret
    doppler:
      url: wss://doppler.local.pcfdev.io:443
    skip_ssl_verify: true

  github_exporter:
    github:
      repos: cloudfoundry-community/prometheus-boshrelease

  prometheus:
    rule_files:
      - /var/vcap/packages/prometheus_cloudfoundry/rules/*.alerts
    scrape_configs:
      - job_name: blackbox
        metrics_path: /probe
        params:
          module:
            - http_2xx
        static_configs:
          - targets:
            - prometheus.io
        relabel_configs:
          - source_labels: [__address__]
            regex: (.*)(:80)?
            target_label: __param_target
            replacement: ${1}
          - source_labels: [__param_target]
            regex: (.*)
            target_label: instance
            replacement: ${1}
          - source_labels: []
            regex: .*
            target_label: __address__
            replacement: localhost:9115
      - job_name: collectd
        static_configs:
          - targets:
            - localhost:9103
      - job_name: consul
        static_configs:
          - targets:
            - localhost:9107
      - job_name: firehose
        static_configs:
          - targets:
            - localhost:9186
      - job_name: github
        static_configs:
          - targets:
            - localhost:9171
      - job_name: graphite
        static_configs:
          - targets:
            - localhost:9108
      - job_name: haproxy
        static_configs:
          - targets:
            - localhost:9101
      - job_name: node
        static_configs:
          - targets:
            - localhost:9100
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
      - job_name: pushgateway
        static_configs:
          - targets:
            - localhost:9091
      - job_name: rabbitmq
        static_configs:
          - targets:
            - localhost:9125
      - job_name: redis
        static_configs:
          - targets:
            - localhost:9121
      - job_name: statsd
        static_configs:
          - targets:
            - localhost:9102
