meta:
  environment: prometheus-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: alertmanager
    networks:
      - name: prometheus1

  - name: prometheus
    networks:
      - name: prometheus1

  - name: grafana
    networks:
      - name: prometheus1

  - name: nginx
    networks:
      - name: prometheus1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: prometheus1
  type: manual
  subnets:
  - range: 10.244.234.0/24
    name: prometheus
    gateway: 10.244.234.1
    static:
      - 10.244.234.2 - 10.244.234.60
