meta:
  environment: (( param "please set meta environment" ))
  dns_root: (( param "please set meta dns_root" ))
  security_groups: (( param "please set meta security_groups" ))

  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: alertmanager
    networks:
      - name: prometheus1

  - name: prometheus
    networks:
      - name: prometheus1

  - name: grafana
    networks:
      - name: prometheus1

  - name: nginx
    networks:
      - name: prometheus1

compilation:
  cloud_properties:
    instance_type: m3.medium

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m3.medium

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: prometheus1
    type: dynamic
    cloud_properties:
      security_groups: (( grab meta.security_groups ))
