meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: alertmanager
    templates:
      - name: alertmanager
        release: prometheus
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z1
    networks: (( param "please set alertmanager networks" ))
    properties:
      alertmanager:
        route:
          receiver: default-receiver
        receivers:
          - name: default-receiver

  - name: prometheus
    templates:
      - name: bosh_alerts
        release: prometheus
      - name: cloudfoundry_alerts
        release: prometheus
      - name: concourse_alerts
        release: prometheus
      - name: consul_alerts
        release: prometheus
      - name: elasticsearch_alerts
        release: prometheus
      - name: grafana_alerts
        release: prometheus
      - name: haproxy_alerts
        release: prometheus
      - name: kubernetes_alerts
        release: prometheus
      - name: mysql_alerts
        release: prometheus
      - name: p_rabbitmq_alerts
        release: prometheus
      - name: p_redis_alerts
        release: prometheus
      - name: postgres_alerts
        release: prometheus
      - name: probe_alerts
        release: prometheus
      - name: prometheus_alerts
        release: prometheus
      - name: rabbitmq_alerts
        release: prometheus
      - name: redis_alerts
        release: prometheus
      - name: prometheus
        release: prometheus
      - name: pushgateway
        release: prometheus
      - name: blackbox_exporter
        release: prometheus
      #- name: bosh_exporter
      #  release: prometheus
      #- name: bosh_tsdb_exporter
      #  release: prometheus
      #- name: cadvisor
      #  release: prometheus
      #- name: cf_exporter
      #  release: prometheus
      #- name: collectd_exporter
      #  release: prometheus
      #- name: consul_exporter
      #  release: prometheus
      #- name: elasticsearch_exporter
      #  release: prometheus
      #- name: firehose_exporter
      #  release: prometheus
      #- name: github_exporter
      #  release: prometheus
      #- name: graphite_exporter
      #  release: prometheus
      #- name: haproxy_exporter
      #  release: prometheus
      #- name: influxdb_exporter
      #  release: prometheus
      #- name: kube_state_metrics_exporter
      #  release: prometheus
      #- name: memcached_exporter
      #  release: prometheus
      #- name: mongodb_exporter
      #  release: prometheus
      #- name: mysqld_exporter
      #  release: prometheus
      #- name: nats_exporter
      #  release: prometheus
      #- name: postgres_exporter
      #  release: prometheus
      #- name: rabbitmq_exporter
      #  release: prometheus
      #- name: redis_exporter
      #  release: prometheus
      #- name: shield_exporter
      #  release: prometheus
      #- name: stackdriver_exporter
      #  release: prometheus
      #- name: statsd_exporter
      #  release: prometheus
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z1
    networks: (( param "please set prometheus networks" ))
    properties:
      blackbox_exporter:
       config:
         modules:
           http_2xx:
             prober: http
             timeout: 5s

      prometheus:
        rule_files:
          - /var/vcap/jobs/bosh_alerts/*.alerts
          - /var/vcap/jobs/cloudfoundry_alerts/*.alerts
          - /var/vcap/jobs/concourse_alerts/*.alerts
          - /var/vcap/jobs/consul_alerts/*.alerts
          - /var/vcap/jobs/elasticsearch_alerts/*.alerts
          - /var/vcap/jobs/grafana_alerts/*.alerts
          - /var/vcap/jobs/haproxy_alerts/*.alerts
          - /var/vcap/jobs/kubernetes_alerts/*.alerts
          - /var/vcap/jobs/mysql_alerts/*.alerts
          - /var/vcap/jobs/p_rabbitmq_alerts/*.alerts
          - /var/vcap/jobs/p_redis_alerts/*.alerts
          - /var/vcap/jobs/postgres_alerts/*.alerts
          - /var/vcap/jobs/probe_alerts/*.alerts
          - /var/vcap/jobs/prometheus_alerts/*.alerts
          - /var/vcap/jobs/rabbitmq_alerts/*.alerts
          - /var/vcap/jobs/redis_alerts/*.alerts
        scrape_configs:
          - job_name: blackbox
            metrics_path: /probe
            params:
              module:
                - http_2xx
            static_configs:
              - targets:
                - prometheus.io
            relabel_configs:
              - source_labels: [__address__]
                regex: (.*)(:80)?
                target_label: __param_target
                replacement: ${1}
              - source_labels: [__param_target]
                regex: (.*)
                target_label: instance
                replacement: ${1}
              - source_labels: []
                regex: .*
                target_label: __address__
                replacement: localhost:9115
          - job_name: bosh
            scrape_interval: 1m
            scrape_timeout: 1m
            static_configs:
              - targets:
                - localhost:9190
          - job_name: bosh_tsdb
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: bosh_tsdb_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9194"
          - job_name: cf
            scrape_interval: 4m
            scrape_timeout: 2m
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: cf_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9193"
          - job_name: collectd
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: collectd_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9103"
          - job_name: consul
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: consul_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9107"
          - job_name: elasticsearch
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: elasticsearch_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9114"
          - job_name: firehose
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: firehose_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9186"
          - job_name: github
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: github_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9171"
          - job_name: grafana
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: grafana_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9261"
          - job_name: graphite
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: graphite_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9108"
          - job_name: haproxy
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: haproxy_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9101"
          - job_name: influxdb
            static_configs:
              - targets:
                - localhost:9122
          - job_name: kubernetes
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: kube_state_metrics_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9188"
          - job_name: memcached
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: memcached_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9150"
          - job_name: mysql
            static_configs:
              - targets:
                - localhost:9104
          - job_name: nats
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: nats_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9118"
          - job_name: node
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: node_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9100"
          - job_name: postgres
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: postgres_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9187"
          - job_name: prometheus
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: prometheus
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9090"
          - job_name: pushgateway
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: pushgateway
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9091"
          - job_name: rabbitmq
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: rabbitmq_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9125"
          - job_name: redis
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: redis_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9121"
          - job_name: shield
            scrape_interval: 4m
            scrape_timeout: 2m
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: shield_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9179"
          - job_name: stackdriver
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: stackdriver_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9255"
          - job_name: statsd
            file_sd_configs:
            - files:
              - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            relabel_configs:
            - source_labels:
              - __meta_bosh_job_process_name
              regex: statsd_exporter
              action: keep
            - source_labels:
              - __address__
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9102"

  - name: grafana
    templates:
      - name: grafana
        release: prometheus
      - name: grafana_exporter
        release: prometheus
      - name: bosh_dashboards
        release: prometheus
      - name: cloudfoundry_dashboards
        release: prometheus
      - name: concourse_dashboards
        release: prometheus
      - name: consul_dashboards
        release: prometheus
      - name: elasticsearch_dashboards
        release: prometheus
      - name: grafana_dashboards
        release: prometheus
      - name: haproxy_dashboards
        release: prometheus
      - name: kubernetes_dashboards
        release: prometheus
      - name: mysql_dashboards
        release: prometheus
      - name: p_rabbitmq_dashboards
        release: prometheus
      - name: p_redis_dashboards
        release: prometheus
      - name: postgres_dashboards
        release: prometheus
      - name: probe_dashboards
        release: prometheus
      - name: prometheus_dashboards
        release: prometheus
      - name: rabbitmq_dashboards
        release: prometheus
      - name: redis_dashboards
        release: prometheus
      - name: system_dashboards
        release: prometheus
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z1
    networks: (( param "please set grafana networks" ))
    properties:
      grafana:
        security:
          admin_password: admin
        dashboards:
          json:
            enabled: true
        prometheus:
          dashboard_files:
            - /var/vcap/jobs/bosh_dashboards/*.json
            - /var/vcap/jobs/cloudfoundry_dashboards/*.json
            - /var/vcap/jobs/concourse_dashboards/*.json
            - /var/vcap/jobs/consul_dashboards/*.json
            - /var/vcap/jobs/elasticsearch_dashboards/*.json
            - /var/vcap/jobs/grafana_dashboards/*.json
            - /var/vcap/jobs/haproxy_dashboards/*.json
            - /var/vcap/jobs/kubernetes_dashboards/*.json
            - /var/vcap/jobs/mysql_dashboards/*.json
            - /var/vcap/jobs/p_rabbitmq_dashboards/*.json
            - /var/vcap/jobs/p_redis_dashboards/*.json
            - /var/vcap/jobs/postgres_dashboards/*.json
            - /var/vcap/jobs/probe_dashboards/*.json
            - /var/vcap/jobs/prometheus_dashboards/*.json
            - /var/vcap/jobs/rabbitmq_dashboards/*.json
            - /var/vcap/jobs/redis_dashboards/*.json
            - /var/vcap/jobs/system_dashboards/*.json
      grafana_exporter:
        grafana:
          uri: http://localhost:3000
          username: admin
          password: admin

  - name: nginx
    templates:
      - name: nginx
        release: prometheus
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z1
    networks: (( param "please set nginx networks" ))
    properties:
      nginx:
        alertmanager:
          auth_username: admin
          auth_password: admin
        prometheus:
          auth_username: admin
          auth_password: admin

networks: (( param "please set networks" ))

properties: {}
