meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: prometheus_z1
    templates:
    - name: prometheus
      release: prometheus
    - name: alertmanager
      release: prometheus
    - name: statsd_bridge
      release: prometheus
    - name: consul_exporter
      release: prometheus
    - name: node_exporter
      release: prometheus
    - name: pushgateway
      release: prometheus
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      prometheus:
        leader_address: (( merge ))

networks: (( merge ))

properties: {}
