---
meta:
  name:    prometheus
  target:  sw
  url:     https://ci.starkandwayne.com
  initial_version: 1.0.0

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   prometheus-boshrelease
    private_key:  (( vault "secret/pipelines/prometheus-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/prometheus-boshrelease/github:token" ))

  bosh-lite:
    target: https://10.58.111.44:25555
    deployment: prometheus-warden

  slack:
    webhook: (( vault "secret/pipelines/prometheus-boshrelease/slack:webhook" ))
    channel: '#botspam'
